//
//  InfoView.swift
//  deTeX
//
//  Created by Venkat on 26/8/20.
//

import SwiftUI

struct InfoView: View {
    
    var body: some View {
        Section(header: Text("How it works").padding(.leading, 20)) {
                Text("DeTeXt uses a MobileNet_v2 PyTorch model trained on the Detexify training data, which was then translated to CoreML using ") +
                Text("coremltools").font(.system(.body, design: .monospaced)) +
                Text(".\n\nThe symbol images are generated by converting PDF files containing each symbol (made with LaTeX) to SVG files. All symbols are typeset in their default font.\n\nThe source code for DeTeXt is available on GitHub under the MIT License.")
                HStack {
                    Image(systemName: "cloud.fill")
                        .font(.body)
                        .aspectRatio(contentMode: .fit)
                        .frame(width:20, alignment: .center)
                        .foregroundColor(.blue)
                    Link("DeTeXt repository", destination: URL(string: "https://github.com/venkatasg/DeTeXt")!)
                        .foregroundColor(.primary)
                }
                HStack {
                    Image(systemName: "wand.and.rays")
                        .font(.body)
                        .aspectRatio(contentMode: .fit)
                        .frame(width:20, alignment: .center)
                        .foregroundColor(.red)
                    Link("Detexify website", destination: URL(string: "http://detexify.kirelabs.org")!)
                        .foregroundColor(.primary)
                }
                HStack {
                    Image(systemName: "doc.fill")
                        .font(.body)
                        .aspectRatio(contentMode: .fit)
                        .frame(width:20, alignment: .center)
                        .foregroundColor(.gray)
                    Link("coremltools Documentation", destination: URL(string: "https://coremltools.readme.io")!)
                        .foregroundColor(.primary)
                }
                HStack {
                    Image(systemName: "function")
                        .font(.body)
                        .aspectRatio(contentMode: .fit)
                        .frame(width:20, alignment: .center)
                        .foregroundColor(.green)
                    Link("MobileNet_V2 PyTorch", destination: URL(string: "https://pytorch.org/docs/stable/torchvision/models.html#torchvision.models.mobilenet_v2")!)
                        .foregroundColor(.primary)
                }
            }
            
        .navigationBarTitle("About DeTeXt", displayMode: .inline)
    }
}


struct Info_Previews: PreviewProvider {
    static var previews: some View {
        InfoView()
    }
}
